# Generated by Django 4.1.2 on 2022-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, default='New Album', max_length=100),
        ),
    ]
